title: Hi, I'm Pippo
description: >-
  He's writing in Bahasa about web technology and experience as a journal  for
  documentation things that he learned, meet him <a
  href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png
repo: 'https://github.com/piharpi/jekyll-klise'
mode: dark
author:
  name: Pippo
  bio: >-
    I work in Data & Analytics at <a href="https://www.project-a.com"
    target="_blank" rel="noopener">Project A</a>.
  username: pippowie
  github: pippowie
  twitter: pippowie
  linkedin: philipp-wiedemann
  avatar: assets/img/profile_square.jpg
url: 'https://pippowie.github.io/home/'
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
